openapi: 3.0.0
info:
  version: 1.0.0
  title: Food Order API
  description: This is an API for a food order reciever
paths:
  /pickup:
    post:
      description: Post a new pickup order
      operationId: app.pickup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
          
  /delivery:
    post:
      description: Post a new delivery order
      operationId: app.delivery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Successful response

components:
    schemas:
      Order:
        type: object 
        required:
          - restaurant_id
          - user_id
          - order_details
          - order_time
        properties:
          restaurant_id:
            type: string
          user_id:
            type: string
          order_details:
            type: object
          order_time:
            type: string